//
//  HTTPMediaTypes+Video.swift
//
//
//  Created by Evan Anderson on 12/30/24.
//

public extension HTTPMediaTypes {
    #HTTPFieldContentType(
        category: "video",
        values: [
            "_1dInterleavedParityfec" : "1d-interleaved-parityfec",
            "_3gpp" : "3gpp",
            "_3gpp2" : "3gpp2",
            "_3gppTT" : "3gpp-tt",
            "av1" : "AV1",
            "bmpeg" : "BMPEG",
            "bt656" : "BT656",
            "celB" : "CelB",
            "dv" : "DV",
            "encaprtp" : "",
            "enc" : "",
            "example" : "",
            "ffv1" : "FFV1",
            "flexfec" : "",
            "h261" : "H261",
            "h263" : "H263",
            "h263_2000" : "H263-2000",
            "h264" : "h264",
            "h264RCDO" : "H264-RCDO",
            "h264SVC" : "H264SVC",
            "h265" : "H265",
            "h266" : "H266",
            "isoSegment" : "iso.segment",
            "jpeg" : "JPEG",
            "jpeg2000" : "",
            "jxsv" : "",
            "matroska" : "",
            "matroska3d" : "matroska-3d",
            "mj2" : "",
            "mp1s" : "MP1S",
            "mp2p" : "MP2P",
            "mp2t" : "MP2T",
            "mp4" : "",
            "mp4VES" : "MP4V-ES",
            "mpv" : "MPV",
            "mpeg" : "",
            "mpeg4Generic" : "mpeg4-generic",
            "nv" : "",
            "ogg" : "",
            "parityfec" : "",
            "pointer" : "",
            "quicktime" : "",
            "raptorfec" : "",
            "raw" : "",
            "rptEncAescm128" : "rtp-enc-aescm128",
            "rtploopback" : "",
            "rtx" : "",
            "scip" : "",
            "smpte291" : "",
            "smpte292m" : "SMPTE292M",
            "ulpfec" : "",
            "vc1" : "",
            "vc2" : "",
            "cctv" : "vnd.CCTV",
            "deceHD" : "vnd.dece.hd",
            "deceMobile" : "vnd.dece.mobile",
            "deceMP4" : "vnd.dece.mp4",
            "decePD" : "vnd.dece.pd",
            "deceSD" : "vnd.dece.sd",
            "deceVideo" : "vnd.dece.video",
            "directvMPEG" : "vnd.directv.mpeg",
            "directvMPEGTTS" : "vnd.directv.mpegTTS",
            "dlnaMpegTTS" : "vnd.dlna.mpeg-tts",
            "dvbFile" : "vnd.dvb.file",
            "fvt" : "vnd.fvt",
            "hnsVideo" : "vnd.hns.video",
            "iptvforum1dparityfec1010" : "vnd.iptvforum.1dparityfec-1010",
            "iptvforum1dparityfec2005" : "vnd.iptvforum.1dparityfec-2005",
            "iptvforum2dparityfec1010" : "vnd.iptvforum.2dparityfec-1010",
            "iptvforum2dparityfec2005" : "vnd.iptvforum.2dparityfec-2005",
            "iptvforumTTSAVC" : "vnd.iptvforum.ttsavc",
            "iptvforumTTSMPEG2" : "vnd.iptvforum.ttsmpeg2",
            "motorolaVideo" : "vnd.motorola.video",
            "motorolaVideop" : "vnd.motorola.videop",
            "mpegurl" : "vnd.mpegurl",
            "pyv" : "vnd.ms-playready.media.pyv",
            "nokiaInterleavedMultimedia" : "vnd.nokia.interleaved-multimedia",
            "nokiaMP4VR" : "vnd.nokia.mp4vr",
            "nokiaVideoVOIP" : "vnd.nokia.videovoip",
            "objectvideo" : "vnd.objectvideo",
            "radgamettoolsBink" : "vnd.radgamettools.bink",
            "radgamettoolsSmacker" : "vnd.radgamettools.smacker",
            "sealedMPEG1" : "vnd.sealed.mpeg1",
            "sealedMPEG4" : "vnd.sealed.mpeg4",
            "sealedSWF" : "vnd.sealed.swf",
            "sealedMediaSoftSealMOV" : "vnd.sealedmedia.softseal.mov",
            "uvvuMP4" : "vnd.uvvu.mp4",
            "youtubeYT" : "vnd.youtube.yt",
            "vivo" : "vnd.vivo",
            "vp8" : "VP8",
            "vp9" : "VP9"
        ]
    )
}