//
//  HTTPMediaTypes+Image.swift
//
//
//  Created by Evan Anderson on 12/30/24.
//

public extension HTTPMediaTypes {
    #HTTPFieldContentType(
        category: "image",
        values: [
            "aces" : "",
            "apng" : "",
            "avci" : "",
            "avcs" : "",
            "avif" : "",
            "bmp" : "",
            "cgm" : "",
            "dicomRLE" : "dicom-rle",
            "dpx" : "",
            "emf" : "",
            "example" : "",
            "fits" : "",
            "g3fax" : "",
            "gif" : "",
            "heic" : "",
            "heicSequence" : "heic-sequence",
            "heif" : "",
            "heifSequence" : "heif-sequence",
            "hej2k" : "",
            "ief" : "",
            "j2c" : "",
            "jls" : "",
            "jp2" : "",
            "jpeg" : "",
            "jph" : "",
            "jphc" : "",
            "jpm" : "",
            "jpx" : "",
            "jxl" : "",
            "jxr" : "",
            "jxrA" : "",
            "jxrS" : "",
            "jxs" : "",
            "jxsc" : "",
            "jxsi" : "",
            "jxss" : "",
            "ktx" : "",
            "ktx2" : "",
            "naplps" : "",
            "png" : "",
            "prsBTIF" : "prs.btif",
            "prsPTI" : "prs.bti",
            "pwgRaster" : "pwg-raster",
            "svgXML" : "svg+xml",
            "t38" : "",
            "tiff" : "",
            "tiffFX" : "tiff-fx",
            "psd" : "vnd.adobe.photoshop",
            "airzipAcceleratorAZV" : "cnd.airzip.accelerator.azv",
            "cnsINF2" : "vnd.cns.inf2",
            "deceGraphic" : "vnd.dece.graphic",
            "djvu" : "vnd.djvu",
            "dwg" : "vnd.dwg",
            "dxf" : "vnd.dxf",
            "dvbSubtitle" : "vnd.dvb.subtitle",
            "fastbidsheet" : "vnd.fastbidsheet",
            "fpx" : "vnd.fpx",
            "fst" : "vnd.fst",
            "fujixeroxEdmicsMMR" : "vnd.fujixerox.edmics-mmr",
            "fujixeroxEdmicsRLC" : "vnd.fujixerox.edmics-rlc",
            "globalGraphicsPGB" : "vnd.globalgraphics.pgb",
            "microsoftIcon" : "vnd.microsoft.icon",
            "mix" : "vnd.mix",
            "msModi" : "vnd.ms-modi",
            "mozillaAPNG" : "vnd.mozilla.apng",
            "netFPX" : "vnd.net-fpx",
            "pcoB16" : "vnd.pco.b16",
            "radiance" : "vnd.radiance",
            "sealedPNG" : "vnd.sealed.png",
            "sealedMediaSoftSealGIF" : "vnd.sealedmedia.softseal.gif",
            "sealedMediaSoftSealJPG" : "vnd.sealedmedia.softseal.jpg",
            "svf" : "vnd.svf",
            "tencentTap" : "vnd.tencent.tap",
            "vtf" : "vnd.valve.source.texture",
            "wapWBMP" : "vnd.wap.wbmp",
            "xiff" : "vnd.xiff",
            "zbrushPCX" : "vnd.zbrush.pcx",
            "webp" : "",
            "wmf" : ""
        ]
    )
}