//
//  HTTPMediaTypes+Text.swift
//
//
//  Created by Evan Anderson on 12/30/24.
//

public extension HTTPMediaTypes {
    #HTTPFieldContentType(
        category: "text",
        values: [
            "_1dInterleavedParityfec" : "1d-interleaved-parityfec",
            "cacheManifest" : "cache-manifest",
            "calendar" : "",
            "cql" : "",
            "cqlExpression" : "cql-expression",
            "cqlIdentifier" : "cql-identifier",
            "css" : "",
            "csv" : "",
            "csvSchema" : "csv-schema",
            "dns" : "",
            "encaprtp" : "",
            "enriched" : "",
            "example" : "",
            "fhirpath" : "",
            "flexfec" : "",
            "fwdred" : "",
            "gff3" : "",
            "grammarRefList" : "grammar-ref-list",
            "hl7v2" : "",
            "html" : "",
            "javascript" : "",
            "jcrCND" : "jcr-cnd",
            "markdown" : "",
            "mizar" : "",
            "n3" : "",
            "parameters" : "",
            "parityfec" : "",
            "plain" : "",
            "provenanceNotation" : "provenance-notation",
            "prsFallensteinRST" : "prs.fallenstein.rst",
            "prsLinesTag" : "prs.lines.tag",
            "prsPropLogic" : "prs.prop.logic",
            "prsTexi" : "prs.texi",
            "raptorfec" : "",
            "red" : "RED",
            "rfc822Headers" : "rfc822-headers",
            "richtext" : "",
            "rtf" : "",
            "rtpEncAescm128" : "rtp-enc-aescm128",
            "rtploopback" : "",
            "rtx" : "",
            "sgml" : "SGML",
            "shaclc" : "",
            "shex" : "",
            "spdx" : "",
            "strings" : "",
            "t140" : "",
            "tabSeparatedValues" : "tab-separated-values",
            "troff" : "",
            "turtle" : "",
            "ulpfec" : "",
            "uriList" : "uri-list",
            "vcard" : "",
            "a" : "vnd.a",
            "abc" : "vnd.abc",
            "asciiArt" : "vnd.ascii-art",
            "curl" : "vnd.curl",
            "debianCopyright" : "vnd.debian.copyright",
            "dmClientScript" : "vnd.DMClientScript",
            "dvbSubtitle" : "vnd.dvb.subtitle",
            "esmertecThemeDescriptor" : "vnd.esmertec.theme-descriptor",
            "exchangeable" : "vnd.exchangeable",
            "familySearchGedcom" : "vnd.familysearch.gedcom",
            "ficlabFLT" : "vnd.ficlab.flt",
            "fmiFlexstor" : "vnd.fmi.flexstor",
            "gml" : "vnd.gml",
            "graphviz" : "vnd.graphviz",
            "hans" : "vnd.hans",
            "hgl" : "vnd.hgl",
            "in3d3dml" : "vnd.in3d.3dml",
            "in3dSpot" : "vnd.in3d.spot",
            "iptcNewsML" : "vnd.IPTC.NewsML",
            "iptcNITF" : "vnd.IPTC.NITF",
            "latexZ" : "vnd.latex-z",
            "motorolaReflex" : "vnd.motorola.reflex",
            "msMediapackage" : "vnd.ms-mediapackage",
            "net2phoneCommCenterCommand" : "vnd.net2phone.commcenter.command",
            "radisysMsmlBasicLayout" : "vnd.radisys.msml-basic-layout",
            "senxWarpscript" : "vnd.senx.warpscript",
            "sunJ2meAppDescriptor" : "vnd.sun.j2me.app-descriptor",
            "sosi" : "vnd.sosi",
            "trolltechLinguist" : "vnd.trolltech.linguist",
            "vcf" : "vnd.vcf",
            "wapSi" : "vnd.wap.si",
            "wapSl" : "vnd.wap.sl",
            "wapWmlscript" : "vnd.wap.wmlscript",
            "zooKCL" : "vnd.zoo.kcl",
            "vtt" : "",
            "wgsl" : "",
            "xml" : "",
            "xmlExternalParsedEntity" : "xml-external-parsed-entity"
        ]
    )
}