//
//  HTTPMediaTypes+Video.swift
//
//
//  Created by Evan Anderson on 12/30/24.
//

public extension HTTPMediaTypes {
    #HTTPFieldContentType(
        category: "video",
        values: [
            "_1dInterleavedParityfec": .init("1d-interleaved-parityfec"),
            "_3gpp": .init("3gpp"),
            "_3gpp2": .init("3gpp2"),
            "_3gppTT": .init("3gpp-tt"),
            "av1": .init("AV1", fileExtensions: ["av1"]),
            "bmpeg": .init("BMPEG"),
            "bt656": .init("BT656"),
            "celB": .init("CelB"),
            "dv": .init("DV"),
            "encaprtp": .init(""),
            "enc": .init(""),
            "example": .init(""),
            "ffv1": .init("FFV1"),
            "flexfec": .init(""),
            "h261": .init("H261"),
            "h263": .init("H263"),
            "h263_2000": .init("H263-2000"),
            "h264": .init("h264"),
            "h264RCDO": .init("H264-RCDO"),
            "h264SVC": .init("H264SVC"),
            "h265": .init("H265"),
            "h266": .init("H266"),
            "isoSegment": .init("iso.segment"),
            "jpeg": .init("JPEG"),
            "jpeg2000": .init(""),
            "jxsv": .init(""),
            "matroska": .init(""),
            "matroska3d": .init("matroska-3d"),
            "mj2": .init(""),
            "mp1s": .init("MP1S"),
            "mp2p": .init("MP2P"),
            "mp2t": .init("MP2T"),
            "mp4": .init(""),
            "mp4VES": .init("MP4V-ES"),
            "mpv": .init("MPV"),
            "mpeg": .init("", fileExtensions: ["mpeg"]),
            "mpeg4Generic": .init("mpeg4-generic"),
            "nv": .init(""),
            "ogg": .init("", fileExtensions: ["ogg"]),
            "parityfec": .init(""),
            "pointer": .init(""),
            "quicktime": .init(""),
            "raptorfec": .init(""),
            "raw": .init(""),
            "rptEncAescm128": .init("rtp-enc-aescm128"),
            "rtploopback": .init(""),
            "rtx": .init(""),
            "scip": .init(""),
            "smpte291": .init(""),
            "smpte292m": .init("SMPTE292M"),
            "ulpfec": .init(""),
            "vc1": .init(""),
            "vc2": .init(""),

            "cctv": .init("vnd.CCTV"),
            "deceHD": .init("vnd.dece.hd"),
            "deceMobile": .init("vnd.dece.mobile"),
            "deceMP4": .init("vnd.dece.mp4"),
            "decePD": .init("vnd.dece.pd"),
            "deceSD": .init("vnd.dece.sd"),
            "deceVideo": .init("vnd.dece.video"),
            "directvMPEG": .init("vnd.directv.mpeg"),
            "directvMPEGTTS": .init("vnd.directv.mpegTTS"),
            "dlnaMpegTTS": .init("vnd.dlna.mpeg-tts"),
            "dvbFile": .init("vnd.dvb.file"),
            "fvt": .init("vnd.fvt"),
            "hnsVideo": .init("vnd.hns.video"),
            "iptvforum1dparityfec1010": .init("vnd.iptvforum.1dparityfec-1010"),
            "iptvforum1dparityfec2005": .init("vnd.iptvforum.1dparityfec-2005"),
            "iptvforum2dparityfec1010": .init("vnd.iptvforum.2dparityfec-1010"),
            "iptvforum2dparityfec2005": .init("vnd.iptvforum.2dparityfec-2005"),
            "iptvforumTTSAVC": .init("vnd.iptvforum.ttsavc"),
            "iptvforumTTSMPEG2": .init("vnd.iptvforum.ttsmpeg2"),
            "motorolaVideo": .init("vnd.motorola.video"),
            "motorolaVideop": .init("vnd.motorola.videop"),
            "mpegurl": .init("vnd.mpegurl"),
            "pyv": .init("vnd.ms-playready.media.pyv"),
            "nokiaInterleavedMultimedia": .init("vnd.nokia.interleaved-multimedia"),
            "nokiaMP4VR": .init("vnd.nokia.mp4vr"),
            "nokiaVideoVOIP": .init("vnd.nokia.videovoip"),
            "objectvideo": .init("vnd.objectvideo"),
            "radgamettoolsBink": .init("vnd.radgamettools.bink"),
            "radgamettoolsSmacker": .init("vnd.radgamettools.smacker"),
            "sealedMPEG1": .init("vnd.sealed.mpeg1"),
            "sealedMPEG4": .init("vnd.sealed.mpeg4"),
            "sealedSWF": .init("vnd.sealed.swf"),
            "sealedMediaSoftSealMOV": .init("vnd.sealedmedia.softseal.mov"),
            "uvvuMP4": .init("vnd.uvvu.mp4"),
            "youtubeYT": .init("vnd.youtube.yt"),
            "vivo": .init("vnd.vivo"),
            "vp8": .init("VP8"),
            "vp9": .init("VP9")
        ]
    )
}