
#if RouteGroup

import Destiny
import SwiftSyntax
import SwiftSyntaxMacros

extension RouteGroup {
    /// Parsing logic for this route group.
    /// 
    /// - Parameters:
    ///   - context: Macro expansion context.
    ///   - version: `HTTPVersion` of the router this route group belongs to.
    ///   - staticMiddleware: Static middleware of the router this route group belongs to.
    ///   - dynamicMiddleware: Dynamic middleware of the router this route group belongs to.
    ///   - function: `FunctionCallExprSyntax` that represents this route group at compile time.
    #if StaticMiddleware
    public static func parse(
        context: some MacroExpansionContext,
        settings: RouterSettings,
        perfectHashSettings: PerfectHashSettings,
        version: HTTPVersion,
        staticMiddleware: [StaticMiddleware],
        dynamicMiddleware: [FunctionCallExprSyntax],
        storage: inout RouterStorage,
        _ function: FunctionCallExprSyntax
    ) -> (decl: DeclSyntax, storage: RouterStorage) {
        var routeGroupStorage = RouterStorage(settings: settings, perfectHashSettings: perfectHashSettings)
        routeGroupStorage.staticMiddleware = staticMiddleware
        return parse(context: context, version: version, routeGroupStorage: &routeGroupStorage, storage: &storage, function)
    }
    #else
    public static func parse(
        context: some MacroExpansionContext,
        settings: RouterSettings,
        perfectHashSettings: PerfectHashSettings,
        version: HTTPVersion,
        dynamicMiddleware: [FunctionCallExprSyntax],
        storage: inout RouterStorage,
        _ function: FunctionCallExprSyntax
    ) -> (decl: DeclSyntax, storage: RouterStorage) {
        var routeGroupStorage = RouterStorage(settings: settings, perfectHashSettings: perfectHashSettings)
        return parse(context: context, version: version, routeGroupStorage: &routeGroupStorage, storage: &storage, function)
    }
    #endif
}

extension RouteGroup {
    static func parse(
        context: some MacroExpansionContext,
        version: HTTPVersion,
        routeGroupStorage: inout RouterStorage,
        storage: inout RouterStorage,
        _ function: FunctionCallExprSyntax
    ) -> (decl: DeclSyntax, storage: RouterStorage) {
        routeGroupStorage.autoGeneratedCaseSensitiveRespondersIndex = storage.autoGeneratedCaseSensitiveRespondersIndex
        routeGroupStorage.autoGeneratedCaseInsensitiveRespondersIndex = storage.autoGeneratedCaseInsensitiveRespondersIndex

        var endpoint = ""
        for f in routeGroupStorage.dynamicMiddleware {
            Router.parseDynamicMiddleware(context: context, function: f, storage: &routeGroupStorage)
        }
        for arg in function.arguments {
            if let label = arg.label?.text {
                switch label {
                case "endpoint":
                    guard let string = arg.expression.stringLiteralString(context: context) else { break }
                    endpoint = string
                case "staticMiddleware":
                    guard let array = arg.expression.arrayElements(context: context) else { break }
                    for arg in array {
                        if let function = arg.expression.functionCall {
                            Router.parseStaticMiddleware(context: context, function: function, storage: &routeGroupStorage)
                        }
                    }
                case "dynamicMiddleware":
                    guard let array = arg.expression.arrayElements(context: context) else { break }
                    for arg in array {
                        if let function = arg.expression.functionCall {
                            Router.parseDynamicMiddleware(context: context, function: function, storage: &routeGroupStorage)
                        }
                    }
                default:
                    context.diagnose(DiagnosticMsg.unhandled(node: arg))
                }
            } else if let function = arg.expression.functionCall {
                Router.parseRoute(context: context, version: version, function: function, storage: &routeGroupStorage)
            }
        }

        let prefixEndpoints = endpoint.split(separator: "/").map({ String($0) })
        let pathComponents = prefixEndpoints.map({ PathComponent.literal($0) })

        let dynamicMiddlewareString = routeGroupStorage.dynamicMiddleware.map({ "\($0)" }).joined(separator: ",\n")

        let immutableDynamicMiddlewareSyntax:String
        if routeGroupStorage.dynamicMiddleware.isEmpty {
            immutableDynamicMiddlewareSyntax = "Optional<CompiledDynamicMiddlewareStorage<DynamicMiddleware>>.none"
        } else {
            immutableDynamicMiddlewareSyntax = "CompiledDynamicMiddlewareStorage((\n\(dynamicMiddlewareString)\n))"
        }

        // TODO: fix

        for i in routeGroupStorage.staticRouteStorage.caseInsensitiveRoutes.indices {
            var (route, function) = routeGroupStorage.staticRouteStorage.caseInsensitiveRoutes[i]
            route.insertPath(contentsOf: prefixEndpoints, at: 0)
            routeGroupStorage.staticRouteStorage.caseInsensitiveRoutes[i] = (route, function)
        }
        let staticRespondersString = routeGroupStorage.staticRoutesResponder(
            context: context,
            isCaseSensitive: false
        )

        for i in routeGroupStorage.dynamicRouteStorage.caseInsensitiveRoutes.indices {
            var (route, function) = routeGroupStorage.dynamicRouteStorage.caseInsensitiveRoutes[i]
            route.insertPath(contentsOf: pathComponents, at: 0)
            routeGroupStorage.dynamicRouteStorage.caseInsensitiveRoutes[i] = (route, function)
        }
        let dynamicRespondersSyntax = routeGroupStorage.dynamicRoutesResponder(
            context: context,
            isCaseSensitive: false
        )

        let compiled = """
        CompiledRouteGroup(
            prefixEndpoints: \(prefixEndpoints),
            immutableDynamicMiddleware: \(immutableDynamicMiddlewareSyntax),
            immutableStaticResponders: \(staticRespondersString),
            immutableDynamicResponders: \(dynamicRespondersSyntax),
            mutableStaticResponders: StaticResponderStorage(),
            mutableDynamicResponders: DynamicResponderStorage()
        )
        """

        storage.autoGeneratedCaseSensitiveRespondersIndex = routeGroupStorage.autoGeneratedCaseSensitiveRespondersIndex
        storage.autoGeneratedCaseInsensitiveRespondersIndex = routeGroupStorage.autoGeneratedCaseInsensitiveRespondersIndex
        return (DeclSyntax(stringLiteral: compiled), routeGroupStorage)
    }
}

#endif