
import DestinyBlueprint
import DestinyDefaults
import SwiftSyntax
import SwiftSyntaxMacros

// MARK: Dynamic routes string
extension Router.Storage {
    mutating func dynamicRoutesString(
        context: some MacroExpansionContext,
        isCaseSensitive: Bool,
        _ routes: [(DynamicRoute, FunctionCallExprSyntax)]
    ) -> String {
        guard !routes.isEmpty else { return "CompiledDynamicResponderStorage(())" }
        let getRouteStartLine:(DynamicRoute) -> String = isCaseSensitive ? { $0.startLine() } : { $0.startLine().lowercased() }
        var autoGeneratedResponderIndex = 0
        var parameterized = [(DynamicRoute, FunctionCallExprSyntax)]()
        var parameterless = [(DynamicRoute, FunctionCallExprSyntax)]()
        var catchall = [(DynamicRoute, FunctionCallExprSyntax)]()
        for route in routes {
            if route.0.path.firstIndex(where: { $0.isParameter }) != nil {
                if route.0.path.firstIndex(where: { $0 == .catchall }) != nil {
                    catchall.append(route)
                } else {
                    parameterized.append(route)
                }
            } else {
                parameterless.append(route)
            }
        }
        let parameterlessString = parameterless.isEmpty ? "" : "\n" + parameterless.compactMap({ route, function in
            let string = getRouteStartLine(route)
            if registeredPaths.contains(string) {
                Router.routePathAlreadyRegistered(context: context, node: function, string)
                return nil
            } else {
                registeredPaths.insert(string)
                let responder = getResponderValue(
                    route: .init(path: string, buffer: .init(string), responder: route.responderDebugDescription),
                    autoGeneratedResponderIndex: &autoGeneratedResponderIndex
                )
                return "// \(string)\n\(responder)"
            }
        }).joined(separator: ",\n\n") + "\n"
        var parameterizedByPathCount = [String]()
        var parameterizedString = ""
        if !parameterized.isEmpty {
            for (route, function) in parameterized {
                if parameterizedByPathCount.count <= route.path.count {
                    for _ in 0...(route.path.count - parameterizedByPathCount.count) {
                        parameterizedByPathCount.append("")
                    }
                }
                var string = route.method.rawNameString() + " /" + route.path.map({ $0.isParameter ? ":any_parameter" : $0.slug }).joined(separator: "/") + " " + route.version.string
                if !registeredPaths.contains(string) {
                    registeredPaths.insert(string)
                    string = getRouteStartLine(route)
                    let responder = getResponderValue(
                        route: .init(path: string, buffer: .init(string), responder: route.responderDebugDescription),
                        autoGeneratedResponderIndex: &autoGeneratedResponderIndex
                    )
                    parameterizedByPathCount[route.path.count].append("\n// \(string)\n" + responder)
                } else {
                    Router.routePathAlreadyRegistered(context: context, node: function, string)
                }
            }
            parameterizedString += "\n" + parameterizedByPathCount.compactMap({ $0.isEmpty ? nil : $0 }).joined(separator: ",\n") + "\n"
        }
        let catchallString = catchall.isEmpty ? "" : "\n" + catchall.compactMap({ route, function in
            let string = getRouteStartLine(route)
            if registeredPaths.contains(string) {
                Router.routePathAlreadyRegistered(context: context, node: function, string)
                return nil
            } else {
                registeredPaths.insert(string)
                let responder = getResponderValue(
                    route: .init(path: string, buffer: .init(string), responder: route.responderDebugDescription),
                    autoGeneratedResponderIndex: &autoGeneratedResponderIndex
                )
                return "// \(string)\n\(responder)"
            }
        }).joined(separator: ",\n\n") + "\n"
        var string = "CompiledDynamicResponderStorage(\n(\n"
        string += parameterlessString + (parameterlessString.isEmpty ? "" : ",\n")
        string += parameterizedString + (parameterizedString.isEmpty ? "" : ",\n")
        string += catchallString
        return string + "\n)\n)"
    }

    mutating func getResponderValue(
        route: Router.Storage.Route,
        autoGeneratedResponderIndex: inout Int
    ) -> String {
        var responder = route.responder
        let logicSplit = responder.split(separator: "logic: {")
        if let responderBody = logicSplit.getPositive(1) {
            let parameters = responderBody.firstIndex(of: "\n")!
            var test = responderBody[responderBody.index(after: parameters)...]
            while test.last != "}" {
                test.removeLast()
            }
            test.removeLast()
            responder = String(test)

            let autoGenStruct = """
            struct AutoGeneratedDynamicResponder\(autoGeneratedResponderIndex)<let pathCount: Int>: DynamicRouteResponderProtocol {
                let path:InlineArray<pathCount, PathComponent>
                let parameterPathIndexes:[Int]
                let defaultResponse:any DynamicResponseProtocol

                init(
                    path: InlineArray<pathCount, PathComponent>,
                    defaultResponse: any DynamicResponseProtocol
                ) {
                    self.path = path
                    parameterPathIndexes = path.indices.compactMap({ path[$0].isParameter ? $0 : nil })
                    self.defaultResponse = defaultResponse
                }

                var debugDescription: String { "" }
                @inlinable var pathComponentsCount: Int { pathCount }
                @inlinable func pathComponent(at index: Int) -> PathComponent { path[index] }

                @inlinable
                func forEachPathComponentParameterIndex(_ yield: (Int) -> Void) {
                    for index in parameterPathIndexes {
                        yield(index)
                    }
                }

                @inlinable
                func respond(
                    to socket: borrowing some HTTPSocketProtocol & ~Copyable,
                    request: inout some HTTPRequestProtocol & ~Copyable,
                    response: inout some DynamicResponseProtocol
                ) async throws {
                    \(responder)
                    try await response.write(to: socket)
                }
            }
            """
            autoGeneratedStructs.append(autoGenStruct)
            autoGeneratedDynamicResponders.append(autoGenStruct)
            var initializer = logicSplit[0]
            if let i = initializer.firstIndex(of: "(") {
                initializer = initializer[initializer.index(after: i)...]
            }
            responder = "AutoGeneratedDynamicResponder\(autoGeneratedResponderIndex)(\(initializer))"
            autoGeneratedResponderIndex += 1
        }
        return "CompiledDynamicResponderStorageRoute(\npath: \(route.buffer),\nresponder: \(responder)\n)"
    }
}