
import DestinyBlueprint
import DestinyDefaults
import SwiftSyntax
import SwiftSyntaxMacros

public struct RouterStorage {
    let visibility:RouterVisibility
    var generatedDecls:[any DeclSyntaxProtocol] = []

    var autoGeneratedDynamicRespondersIndex = 0
    var autoGeneratedCaseSensitiveRespondersIndex = 0
    var autoGeneratedCaseInsensitiveRespondersIndex = 0
    var upgradeExistentialDynamicMiddleware:[FunctionCallExprSyntax] = []

    var dynamicMiddleware:[FunctionCallExprSyntax] = []
    var dynamicRedirects:[(any RedirectionRouteProtocol, SyntaxProtocol)] = []
    var dynamicRoutes:[(DynamicRoute, FunctionCallExprSyntax)] = []

    var staticMiddleware:[CompiledStaticMiddleware] = []
    var staticRedirects:[(any RedirectionRouteProtocol, SyntaxProtocol)] = []
    var staticRoutes:[(StaticRoute, FunctionCallExprSyntax)] = []
    
    var routeGroups:[any DeclSyntaxProtocol] = []

    var conditionalResponders:[RoutePath:any ConditionalRouteResponderProtocol] = [:]
    var registeredPaths:Set<String> = []

    mutating func routeGroupsString(context: some MacroExpansionContext) -> String {
        var string = ""
        if !routeGroups.isEmpty {
            string += "\n" + routeGroups.map({ "\($0)" }).joined(separator: ",\n") + "\n"
        }
        return string
    }

    func staticMiddlewareString() -> String {
        return staticMiddleware.isEmpty ? "" : "\n" + staticMiddleware.map({ "\($0)" }).joined(separator: ",\n") + "\n"
    }

    lazy var autoGeneratedOpaqueDynamicMiddleware: String? = {
        guard !upgradeExistentialDynamicMiddleware.isEmpty else { return nil }
        for (i, function) in upgradeExistentialDynamicMiddleware.enumerated() {
            let functionString = "\(function.arguments.first!.expression.as(ClosureExprSyntax.self)!.statements)"
            let name = "OpaqueDynamicMiddleware\(i)"
            let string = """
            // MARK: \(name)
            struct \(name): OpaqueDynamicMiddlewareProtocol {

                @inlinable
                func customLogic(
                    request: inout some HTTPRequestProtocol & ~Copyable,
                    response: inout some DynamicResponseProtocol
                ) throws(MiddlewareError) {
                    \(functionString)
                }

                @inlinable
                func handle(
                    request: inout some HTTPRequestProtocol & ~Copyable,
                    response: inout some DynamicResponseProtocol
                ) throws(MiddlewareError) -> Bool {
                    try await customLogic(request: &request, response: &response)
                    return true
                }
            }
            """
            try! generatedDecls.append(StructDeclSyntax(.init(stringLiteral: string)))
        }
        return ""
    }()

    mutating func dynamicMiddlewareString(mutable: Bool) -> String {
        var string = "\(mutable ? "" : "Compiled")OpaqueDynamicMiddlewareStorage("
        if mutable {
            string += "["
        } else {
            string += "("
        }
        if autoGeneratedOpaqueDynamicMiddleware != nil {
            string += "\n\(upgradeExistentialDynamicMiddleware.enumerated().map({ "OpaqueDynamicMiddleware\($0.offset)()" }).joined(separator: ",\n")),\n"
        }
        if !dynamicMiddleware.isEmpty {
            string += "\n\(dynamicMiddleware.map({ "\($0)" }).joined(separator: ",\n"))\n"
        }
        if mutable {
            string += "]"
        } else {
            string += ")"
        }
        return string + ")"
    }

    mutating func staticResponsesSyntax(
        mutable: Bool,
        context: some MacroExpansionContext,
        caseSensitive: Bool
    ) -> String {
        return staticRoutesSyntax(
            mutable: mutable,
            context: context,
            isCaseSensitive: caseSensitive,
            redirects: staticRedirects.filter({ $0.0.isCaseSensitive == caseSensitive }),
            middleware: staticMiddleware,
            routes: staticRoutes.filter({ $0.0.isCaseSensitive == caseSensitive })
        )
    }

    mutating func dynamicResponsesString(
        mutable: Bool,
        context: some MacroExpansionContext,
        caseSensitive: Bool
    ) -> String {
        return dynamicRoutesSyntax(
            mutable: mutable,
            context: context,
            isCaseSensitive: caseSensitive,
            routes: dynamicRoutes.filter({ $0.0.isCaseSensitive == caseSensitive })
        )
    }

    func conditionalRespondersString() -> String {
        var string:String
        if conditionalResponders.isEmpty {
            string = ":"
        } else {
            string = ""
            for (routePath, route) in conditionalResponders {
                string += "\n\(routePath.comment)\n\(routePath.path) : \(route.debugDescription),"
            }
            string.removeLast()
            string += "\n"
        }
        return string
    }
}

extension RouterStorage {
    struct Route {
        let startLine:String
        let buffer:DestinyRoutePathType
        let responder:String

        var path: Substring {
            startLine.split(separator: " ")[1]
        }
        var paths: [Substring] {
            path.split(separator: "/")
        }
    }
}