
import DestinyBlueprint
import DestinyDefaults
import SwiftDiagnostics
import SwiftSyntax
import SwiftSyntaxMacros

// MARK: Static routes string
extension RouterStorage {
    mutating func staticRoutesSyntax(
        mutable: Bool,
        context: some MacroExpansionContext,
        isCaseSensitive: Bool,
        redirects: [(any RedirectionRouteProtocol, SyntaxProtocol)],
        middleware: [CompiledStaticMiddleware],
        routes: [(StaticRoute, FunctionCallExprSyntax)]
    ) -> String? {
        guard !routes.isEmpty else { return nil }
        var routePaths = [String]()
        var literalRouteResponders = [String]()
        var routeResponders = [String]()
        let getRedirectRouteStartLine:(any RedirectionRouteProtocol) -> String = isCaseSensitive ? { route in
            return route.fromStartLine()
        } : { route in
            return route.fromStartLine().lowercased()
        }
        let getResponderValue:(RouterStorage.Route) -> String = {
            let responder = $0.responder
            return "// \($0.startLine)\nCompiledStaticResponderStorageRoute(\npath: \($0.buffer),\nresponder: \(responder)\n)"
        }
        if !redirects.isEmpty {
            for (route, function) in redirects {
                var string = getRedirectRouteStartLine(route)
                if registeredPaths.contains(string) {
                    Router.routePathAlreadyRegistered(context: context, node: function, string)
                } else {
                    registeredPaths.insert(string)
                    do throws(AnyError) {
                        let responder = try IntermediateResponseBody(type: .stringWithDateHeader, "").responderDebugDescription(route.response())
                        routeResponders.append(getResponderValue(.init(startLine: string, buffer: .init(&string), responder: responder)))

                        routePaths.append("\(string)")
                        literalRouteResponders.append(responder)
                    } catch {
                        context.diagnose(Diagnostic(node: function, message: DiagnosticMsg(id: "staticRedirectError", message: "\(error)")))
                    }
                }
            }
        }
        appendStaticRoutes(
            context: context,
            middleware: middleware,
            isCaseSensitive: isCaseSensitive,
            routes: routes,
            routePaths: &routePaths,
            routeResponders: &routeResponders,
            literalRouteResponders: &literalRouteResponders
        )

        let random = isCaseSensitive ? autoGeneratedCaseSensitiveRespondersIndex : autoGeneratedCaseInsensitiveRespondersIndex

        let namePrefix = "Case\(isCaseSensitive ? "S" : "Ins")ensitive"
        var enumDecl = StructDeclSyntax(
            leadingTrivia: "// MARK: \(namePrefix)StaticResponderStorage\(random)\n\(visibility)",
            name: "\(raw: namePrefix)StaticResponderStorage\(raw: random)",
            inheritanceClause: .init(
                inheritedTypes: .init(arrayLiteral:
                    .init(type: TypeSyntax.init(stringLiteral: "StaticResponderStorageProtocol"), trailingComma: ","),
                    .init(type: TypeSyntax.init(stringLiteral: "Copyable"))
                )
            ),
            memberBlock: .init(members: .init())
        )

        generatedDecls.append(enumDecl)    
        if isCaseSensitive {
            autoGeneratedCaseSensitiveRespondersIndex += 1
        } else {
            autoGeneratedCaseInsensitiveRespondersIndex += 1
        }
        return "\(enumDecl.name.text)()"
    }
    func responseBodyResponderDebugDescription(
        body: (any ResponseBodyProtocol)?,
        response: HTTPResponseMessage
    ) throws(HTTPMessageError) -> String? {
        guard let body else { return nil }
        let s:String?
        if let v = body as? String {
            s = try v.responderDebugDescription(response)
        } else if let v = body as? IntermediateResponseBody {
            s = v.responderDebugDescription(response)

        } else {
            s = nil
        }
        return s
    }
}