//
//  HTTPMediaTypes+Image.swift
//
//
//  Created by Evan Anderson on 12/30/24.
//

extension HTTPMediaType {
    #HTTPFieldContentType(
        category: "image",
        values: [
            "aces": .init(""),
            "apng": .init(""),
            "avci": .init(""),
            "avcs": .init(""),
            "avif": .init(""),
            "bmp": .init(""),
            "cgm": .init(""),
            "dicomRLE": .init("dicom-rle"),
            "dpx": .init(""),
            "emf": .init(""),
            "example": .init(""),
            "fits": .init(""),
            "g3fax": .init(""),
            "gif": .init("", fileExtensions: ["gif"]),
            "heic": .init(""),
            "heicSequence": .init("heic-sequence"),
            "heif": .init(""),
            "heifSequence": .init("heif-sequence"),
            "hej2k": .init(""),
            "ief": .init(""),
            "j2c": .init(""),
            "jls": .init(""),
            "jp2": .init(""),
            "jpeg": .init("", fileExtensions: ["jpeg", "jpg"]),
            "jph": .init(""),
            "jphc": .init(""),
            "jpm": .init(""),
            "jpx": .init(""),
            "jxl": .init(""),
            "jxr": .init(""),
            "jxrA": .init(""),
            "jxrS": .init(""),
            "jxs": .init(""),
            "jxsc": .init(""),
            "jxsi": .init(""),
            "jxss": .init(""),
            "ktx": .init(""),
            "ktx2": .init(""),
            "naplps": .init(""),
            "png": .init("", fileExtensions: ["png"]),
            "prsBTIF": .init("prs.btif"),
            "prsPTI": .init("prs.bti"),
            "pwgRaster": .init("pwg-raster"),
            "svgXML": .init("svg+xml"),
            "t38": .init(""),
            "tiff": .init(""),
            "tiffFX": .init("tiff-fx"),

            "psd": .init("vnd.adobe.photoshop"),
            "airzipAcceleratorAZV": .init("cnd.airzip.accelerator.azv"),
            "cnsINF2": .init("vnd.cns.inf2"),
            "deceGraphic": .init("vnd.dece.graphic"),
            "djvu": .init("vnd.djvu"),
            "dwg": .init("vnd.dwg"),
            "dxf": .init("vnd.dxf"),
            "dvbSubtitle": .init("vnd.dvb.subtitle"),
            "fastbidsheet": .init("vnd.fastbidsheet"),
            "fpx": .init("vnd.fpx"),
            "fst": .init("vnd.fst"),
            "fujixeroxEdmicsMMR": .init("vnd.fujixerox.edmics-mmr"),
            "fujixeroxEdmicsRLC": .init("vnd.fujixerox.edmics-rlc"),
            "globalGraphicsPGB": .init("vnd.globalgraphics.pgb"),
            "microsoftIcon": .init("vnd.microsoft.icon"),
            "mix": .init("vnd.mix"),
            "msModi": .init("vnd.ms-modi"),
            "mozillaAPNG": .init("vnd.mozilla.apng"),
            "netFPX": .init("vnd.net-fpx"),
            "pcoB16": .init("vnd.pco.b16"),
            "radiance": .init("vnd.radiance"),
            "sealedPNG": .init("vnd.sealed.png"),
            "sealedMediaSoftSealGIF": .init("vnd.sealedmedia.softseal.gif"),
            "sealedMediaSoftSealJPG": .init("vnd.sealedmedia.softseal.jpg"),
            "svf": .init("vnd.svf"),
            "tencentTap": .init("vnd.tencent.tap"),
            "vtf": .init("vnd.valve.source.texture"),
            "wapWBMP": .init("vnd.wap.wbmp"),
            "xiff": .init("vnd.xiff"),
            "zbrushPCX": .init("vnd.zbrush.pcx"),
            "webp": .init(""),
            "wmf": .init("")
        ]
    )
}